In [ ]:
import numpy as np
import pandas as pd

### Load datasets

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/bapujik/dataSets/main/zomato.csv",encoding="latin1")

In [ ]:
print(data.head())

   Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City
1        6304287        Izakaya Kikufuji           162       Makati City
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City
3        6318506                    Ooma           162  Mandaluyong City
4        6314302             Sambo Kojin           162  Mandaluyong City

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3  Third Floor, Mega Fashion Hall, SM Megamall, O...
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...

                                     Locality  \
0   Century City Mall, Poblacion, Makati City
1  Little Tokyo, Legaspi Village, Makati City
2  Edsa Shangri-La, Ortigas, Mandaluyong City
3      SM Megamall, Ortigas, Mandaluyong City
4      SM Megamall, Ortigas, Mandaluyong City

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes
1                          Japanese  ...  Botswana Pula(P)               Yes
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes
3                   Japanese, Sushi  ...  Botswana Pula(P)                No
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3
1                  No                No                   No           3
2                  No                No                   No           4
3                  No                No                   No           4
4                  No                No                   No           4

   Aggregate rating  Rating color Rating text Votes
0               4.8    Dark Green   Excellent   314
1               4.5    Dark Green   Excellent   591
2               4.4         Green   Very Good   270
3               4.9    Dark Green   Excellent   365
4               4.8    Dark Green   Excellent   229

[5 rows x 21 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
country=pd.read_csv("https://raw.githubusercontent.com/bapujik/dataSets/main/Country-Code1.csv")

In [ ]:
print(country.head())

   Country Code    Country
0             1      India
1            14  Australia
2            30     Brazil
3            37     Canada
4            94  Indonesia

### df.describe() generates descriptive statistics of the data within the DataFrame df.  It calculates various summary statistics for each numerical column in the DataFrame, such as count, mean, standard deviation, minimum, maximum, and quartiles.

### Count: The count represents the number of non-null (non-missing) values in each numerical column. This statistic provides an indication of the completeness of the data. If the count for a column is less than the total number of rows in the DataFrame, it suggests missing values in that column.

### Mean (Average): The mean is the arithmetic average of all the values in a column. It gives a measure of the central tendency of the data. However, it can be sensitive to outliers, especially in skewed distributions.

### Standard Deviation:The standard deviation measures the dispersion or spread of the values around the mean. A high standard deviation indicates that the values in the column are spread out over a wide range from the mean, while a low standard deviation suggests that the values are clustered closely around the mean.
### 25th Percentile (First Quartile):The 25th percentile, also known as the first quartile (Q1), divides the data into four equal parts, with 25% of the data falling below this value. It gives insight into the spread of the lower values in the data distribution.

### Median (50th Percentile, Second Quartile):The median is the middle value of the sorted column data.It represents the value below which 50% of the data falls and above which the other 50% falls. It's also the second quartile (Q2). Median is often preferred over mean when dealing with skewed distributions or datasets containing outliers because it's less affected by extreme values.
### 75th Percentile (Third Quartile): The 75th percentile, or third quartile (Q3), divides the data into four equal parts, with 75% of the data falling below this value. It provides insight into the spread of the higher values in the data distribution.

In [ ]:
data.describe()

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
data["Aggregate rating"]

0       4.8
1       4.5
2       4.4
3       4.9
4       4.8
       ...
9546    4.1
9547    4.2
9548    3.7
9549    4.0
9550    4.0
Name: Aggregate rating, Length: 9551, dtype: float64

In [ ]:
data["Aggregate rating"].mean()

2.66637001361114

In [ ]:
data["Votes"].mean()

156.909747670401

In [ ]:
country

    Country Code         Country
0              1           India
1             14       Australia
2             30          Brazil
3             37          Canada
4             94       Indonesia
5            148     New Zealand
6            162     Phillipines
7            166           Qatar
8            184       Singapore
9            189    South Africa
10           191       Sri Lanka
11           208          Turkey
12           214             UAE
13           215  United Kingdom
14           216   United States

In [ ]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Code  15 non-null     int64
 1   Country       15 non-null     object
dtypes: int64(1), object(1)
memory usage: 368.0+ bytes

In [ ]:
data1=pd.merge(data,country,on="Country Code")

In [ ]:
data1.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
 21  Country               9551 non-null   object
dtypes: float64(3), int64(5), object(14)
memory usage: 1.6+ MB

In [ ]:
data1.Country

0       Phillipines
1       Phillipines
2       Phillipines
3       Phillipines
4       Phillipines
           ...
9546         Turkey
9547         Turkey
9548         Turkey
9549         Turkey
9550         Turkey
Name: Country, Length: 9551, dtype: object

In [ ]:
data1.Country=="India"

0       False
1       False
2       False
3       False
4       False
        ...
9546    False
9547    False
9548    False
9549    False
9550    False
Name: Country, Length: 9551, dtype: bool

In [ ]:
data1[data1.Country=="India"]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
624,3400025,Jahanpanah,1,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",78.011544,27.161661,"North Indian, Mughlai",...,No,No,No,No,3,3.9,Yellow,Good,140,India
625,3400341,Rangrezz Restaurant,1,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",0.000000,0.000000,"North Indian, Mughlai",...,No,No,No,No,2,3.5,Yellow,Good,71,India
626,3400005,Time2Eat - Mama Chicken,1,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,"Agra Cantt, Agra",78.011608,27.160832,North Indian,...,No,No,No,No,2,3.6,Yellow,Good,94,India
627,3400021,Chokho Jeeman Marwari Jain Bhojanalya,1,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,"Civil Lines, Agra",77.998092,27.195928,Rajasthani,...,No,No,No,No,2,4.0,Green,Very Good,87,India
628,3400017,Pinch Of Spice,1,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,"Civil Lines, Agra",78.007553,27.201725,"North Indian, Chinese, Mughlai",...,No,No,No,No,3,4.2,Green,Very Good,177,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9271,2800100,D Cabana,1,Vizag,"Beach Road, Near Bus Stop, Sagar Nagar, Visakh...",Sagar Nagar,"Sagar Nagar, Vizag",83.361377,17.764287,"Continental, Seafood, Chinese, North Indian, B...",...,No,No,No,No,2,3.6,Yellow,Good,193,India
9272,2800418,Kaloreez,1,Vizag,"Plot 95, Opposite St. Lukes Nursing School, Da...",Siripuram,"Siripuram, Vizag",0.000000,0.000000,"Cafe, North Indian, Chinese",...,No,No,No,No,2,3.7,Yellow,Good,85,India
9273,2800881,Plot 17,1,Vizag,"Plot 17, Gangapur Layout, Siripuram, Vizag",Siripuram,"Siripuram, Vizag",83.315281,17.719539,"Burger, Pizza, Biryani",...,No,No,No,No,2,4.3,Green,Very Good,172,India
9274,2800042,Vista - The Park,1,Vizag,"The Park, Beach Road, Pedda Waltair, Lawsons B...","The Park, Lawsons Bay","The Park, Lawsons Bay, Vizag",83.336840,17.721182,"American, North Indian, Thai, Continental",...,No,No,No,No,4,3.8,Yellow,Good,74,India
9275,2800019,Flying Spaghetti Monster,1,Vizag,"10-50-12/F2, Sai Dakshata Complex, Beside Leno...",Waltair Uplands,"Waltair Uplands, Vizag",83.314942,17.721119,Italian,...,No,No,No,No,3,4.4,Green,Very Good,316,India

In [ ]:
res_India=data1[data1.Country=="India"]

In [ ]:
res_India.tail()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
9271,2800100,D Cabana,1,Vizag,"Beach Road, Near Bus Stop, Sagar Nagar, Visakh...",Sagar Nagar,"Sagar Nagar, Vizag",83.361377,17.764287,"Continental, Seafood, Chinese, North Indian, B...",...,No,No,No,No,2,3.6,Yellow,Good,193,India
9272,2800418,Kaloreez,1,Vizag,"Plot 95, Opposite St. Lukes Nursing School, Da...",Siripuram,"Siripuram, Vizag",0.000000,0.000000,"Cafe, North Indian, Chinese",...,No,No,No,No,2,3.7,Yellow,Good,85,India
9273,2800881,Plot 17,1,Vizag,"Plot 17, Gangapur Layout, Siripuram, Vizag",Siripuram,"Siripuram, Vizag",83.315281,17.719539,"Burger, Pizza, Biryani",...,No,No,No,No,2,4.3,Green,Very Good,172,India
9274,2800042,Vista - The Park,1,Vizag,"The Park, Beach Road, Pedda Waltair, Lawsons B...","The Park, Lawsons Bay","The Park, Lawsons Bay, Vizag",83.336840,17.721182,"American, North Indian, Thai, Continental",...,No,No,No,No,4,3.8,Yellow,Good,74,India
9275,2800019,Flying Spaghetti Monster,1,Vizag,"10-50-12/F2, Sai Dakshata Complex, Beside Leno...",Waltair Uplands,"Waltair Uplands, Vizag",83.314942,17.721119,Italian,...,No,No,No,No,3,4.4,Green,Very Good,316,India

In [ ]:
res_India.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
624,3400025,Jahanpanah,1,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",78.011544,27.161661,"North Indian, Mughlai",...,No,No,No,No,3,3.9,Yellow,Good,140,India
625,3400341,Rangrezz Restaurant,1,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",0.000000,0.000000,"North Indian, Mughlai",...,No,No,No,No,2,3.5,Yellow,Good,71,India
626,3400005,Time2Eat - Mama Chicken,1,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,"Agra Cantt, Agra",78.011608,27.160832,North Indian,...,No,No,No,No,2,3.6,Yellow,Good,94,India
627,3400021,Chokho Jeeman Marwari Jain Bhojanalya,1,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,"Civil Lines, Agra",77.998092,27.195928,Rajasthani,...,No,No,No,No,2,4.0,Green,Very Good,87,India
628,3400017,Pinch Of Spice,1,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,"Civil Lines, Agra",78.007553,27.201725,"North Indian, Chinese, Mughlai",...,No,No,No,No,3,4.2,Green,Very Good,177,India

In [ ]:
NCR=["New Delhi","Gurgaon","Noida","Faridabad"]

In [ ]:
print(NCR)

['New Delhi', 'Gurgaon', 'Noida', 'Faridabad']

In [ ]:
NCR[3]

'Faridabad'

In [ ]:
res_India.City

624      Agra
625      Agra
626      Agra
627      Agra
628      Agra
        ...
9271    Vizag
9272    Vizag
9273    Vizag
9274    Vizag
9275    Vizag
Name: City, Length: 8652, dtype: object

In [ ]:
res_India[res_India.City==NCR[3]]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
865,301728,Desire Foods,1,Faridabad,"G 25/22, Main Road, 40 Feet, Molarband Extensi...",Badarpur Border,"Badarpur Border, Faridabad",77.306640,28.490059,"Chinese, Fast Food, Bakery",...,No,No,No,No,1,2.9,Orange,Average,4,India
866,5992,Knight Rock,1,Faridabad,"11/6, Delhi Mathura Road, Near Bharat Petrol P...",Badarpur Border,"Badarpur Border, Faridabad",77.304776,28.490157,"North Indian, Chinese",...,No,No,No,No,2,2.8,Orange,Average,16,India
867,301730,Punjab Restaurant,1,Faridabad,"Main 40 Feet Road, Molarband Extension, Badarp...",Badarpur Border,"Badarpur Border, Faridabad",77.305563,28.490137,North Indian,...,No,No,No,No,1,2.8,Orange,Average,8,India
868,301729,Raju Dhaba,1,Faridabad,"Main 40 Feet Road, Molarband Extension, Badarp...",Badarpur Border,"Badarpur Border, Faridabad",77.306102,28.490098,North Indian,...,No,No,No,No,1,2.9,Orange,Average,8,India
869,301731,Rakheja Bakery,1,Faridabad,"Main 40 Feet Road, Molarband Extension, Badarp...",Badarpur Border,"Badarpur Border, Faridabad",77.305745,28.490062,Bakery,...,No,No,No,No,1,2.8,Orange,Average,7,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,312967,Tasty Bites,1,Faridabad,"A-8, A-60 Feet Road, Pul Prahladpur, Suraj Kun...",Suraj Kund,"Suraj Kund, Faridabad",77.289912,28.499714,"South Indian, Chinese, North Indian",...,No,No,No,No,1,0.0,White,Not rated,2,India
1112,18449815,The Street- Curries & Grills,1,Faridabad,"57, EWA, Charmwood Village, Suraj Kund, Faridabad",Suraj Kund,"Suraj Kund, Faridabad",77.290565,28.489496,"North Indian, Mughlai, Continental",...,No,No,No,No,2,0.0,White,Not rated,1,India
1113,2680,Bakers Delight - The Atrium,1,Faridabad,"The Atrium Hotel, Shooting Range Road, Suraj K...","The Atrium, Suraj Kund","The Atrium, Suraj Kund, Faridabad",77.283011,28.489796,"Bakery, Desserts",...,No,No,No,No,2,3.0,Orange,Average,10,India
1114,2679,On The Rocks - The Atrium,1,Faridabad,"The Atrium Hotel, Shooting Range Road, Suraj K...","The Atrium, Suraj Kund","The Atrium, Suraj Kund, Faridabad",77.283011,28.489796,Finger Food,...,Yes,No,No,No,3,3.1,Orange,Average,18,India
1115,8417,World Cafe - Vibe by The LaLiT Traveller,1,Faridabad,"Vibe by The Lalit Traveller, 12/7, Sector 35, ...","Vibe by The LaLit Traveller, Mathura Road","Vibe by The LaLit Traveller, Mathura Road, Far...",77.306073,28.472912,"North Indian, Continental, Chinese",...,Yes,No,No,No,3,3.3,Orange,Average,56,India

In [ ]:
res_NCR=res_India[(res_India.City==NCR[0])|(res_India.City==NCR[1])|(res_India.City==NCR[2])|(res_India.City==NCR[3])]

In [ ]:
res_NCR.City.unique()

array(['Faridabad', 'Gurgaon', 'New Delhi', 'Noida'], dtype=object)

In [ ]:
res_NCR.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7922 entries, 865 to 9112
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         7922 non-null   int64
 1   Restaurant Name       7922 non-null   object
 2   Country Code          7922 non-null   int64
 3   City                  7922 non-null   object
 4   Address               7922 non-null   object
 5   Locality              7922 non-null   object
 6   Locality Verbose      7922 non-null   object
 7   Longitude             7922 non-null   float64
 8   Latitude              7922 non-null   float64
 9   Cuisines              7922 non-null   object
 10  Average Cost for two  7922 non-null   int64
 11  Currency              7922 non-null   object
 12  Has Table booking     7922 non-null   object
 13  Has Online delivery   7922 non-null   object
 14  Is delivering now     7922 non-null   object
 15  Switch to order menu  7922 non-null   object
 16  Price range           7922 non-null   int64
 17  Aggregate rating      7922 non-null   float64
 18  Rating color          7922 non-null   object
 19  Rating text           7922 non-null   object
 20  Votes                 7922 non-null   int64
 21  Country               7922 non-null   object
dtypes: float64(3), int64(5), object(14)
memory usage: 1.4+ MB

In [ ]:
data_new_delhi=res_NCR[["Restaurant Name","Cuisines","Locality","Aggregate rating","Votes"]]

In [ ]:
data_new_delhi.head()

,Restaurant Name,Cuisines,Locality,Aggregate rating,Votes
865,Desire Foods,"Chinese, Fast Food, Bakery",Badarpur Border,2.9,4
866,Knight Rock,"North Indian, Chinese",Badarpur Border,2.8,16
867,Punjab Restaurant,North Indian,Badarpur Border,2.8,8
868,Raju Dhaba,North Indian,Badarpur Border,2.9,8
869,Rakheja Bakery,Bakery,Badarpur Border,2.8,7

In [ ]:
C=data_new_delhi["Aggregate rating"].mean()

In [ ]:
print(C)

2.3958343852562485

In [ ]:
data_new_delhi["Votes"]

865      4
866     16
867      8
868      8
869      7
        ..
9108    34
9109     1
9110     3
9111     0
9112     1
Name: Votes, Length: 7922, dtype: int64

### The quantile, specifically the 90th percentile, is a value below which 90% of the data points fall. In other words, 90% of the data points are less than or equal to this value.
### It's a measure of statistical dispersion that indicates the point below which a given fraction of observations in a group of observations fall.

In [ ]:
# Example dataset
data = [20, 10, 30, 50, 40]

# Sort the dataset
sorted_data = sorted(data)
print("Sorted data:", sorted_data)

Sorted data: [10, 20, 30, 40, 50]

In [ ]:
# Calculate the index corresponding to the 90th percentile
index_90th_percentile = int(0.9 * (len(sorted_data) - 1))
print("Index for the 90th percentile:", index_90th_percentile)

Index for the 90th percentile: 3

In [ ]:
# Retrieve the value at the calculated index
p90_nearest_rank = sorted_data[index_90th_percentile]
print("90th percentile (nearest rank interpolation):", p90_nearest_rank)

90th percentile (nearest rank interpolation): 40

In [ ]:
m=data_new_delhi["Votes"].quantile(0.9)

In [ ]:
m

234.0

In [ ]:
data_new_delhi["Votes"]

865      4
866     16
867      8
868      8
869      7
        ..
9108    34
9109     1
9110     3
9111     0
9112     1
Name: Votes, Length: 7922, dtype: int64

In [ ]:
data_new_delhi["Votes"].max()

7931

In [ ]:
data_new_delhi["Votes"].min()

0

In [ ]:
data_new_delhi["Votes"].mean()

106.0936632163595

In [ ]:
m

234.0

In [ ]:
data_new_delhi["Votes"]>=m

865     False
866     False
867     False
868     False
869     False
        ...
9108    False
9109    False
9110    False
9111    False
9112    False
Name: Votes, Length: 7922, dtype: bool

In [ ]:
q_restuarant=data_new_delhi.copy().loc[data_new_delhi["Votes"]>=m]

In [ ]:
q=data_new_delhi[data_new_delhi["Votes"]>=m]

In [ ]:
q.head()

,Restaurant Name,Cuisines,Locality,Aggregate rating,Votes
884,Berco's,"Chinese, Thai","Crown Interiorz Mall, Sector 35, Faridabad",3.8,508
891,Barbeque Nation,North Indian,"Crown Interiorz Mall, Sector 35, Faridabad",4.0,299
892,Yo! China,Chinese,"Crown Interiorz Mall, Sector 35, Faridabad",4.1,239
943,Cafe Parmesan,Italian,Sector 15,4.5,799
949,Chickenette,"Raw Meats, North Indian, Chinese, Fast Food",Sector 15,3.7,280

In [ ]:
q_restuarant.head()

,Restaurant Name,Cuisines,Locality,Aggregate rating,Votes
884,Berco's,"Chinese, Thai","Crown Interiorz Mall, Sector 35, Faridabad",3.8,508
891,Barbeque Nation,North Indian,"Crown Interiorz Mall, Sector 35, Faridabad",4.0,299
892,Yo! China,Chinese,"Crown Interiorz Mall, Sector 35, Faridabad",4.1,239
943,Cafe Parmesan,Italian,Sector 15,4.5,799
949,Chickenette,"Raw Meats, North Indian, Chinese, Fast Food",Sector 15,3.7,280

### Bayesian average to compute average rating, properly
ref: https://en.wikipedia.org/wiki/Bayesian_average

![image.png]()

In [ ]:
def weighted_rating(x,m=m,C=C):
    v=x["Votes"]
    R=x["Aggregate rating"]
    return (v/(v+m)*R) + (m/(m+v)*C)

### df.apply(): The apply() function in pandas is a powerful method used to apply a function along an axis of a DataFrame.

### df.apply(func, axis=0, raw=False, result_type=None, args=(), **kwds)
### func: The function to apply to each element or row/column of the DataFrame
### axis: The axis along which the function will be applied. Axis 0 applies the function to each column, while axis 1 applies it to each row.
### raw: If True, the passed function will receive ndarray objects instead of Series objects.
### result_type: Specifies the type of the result. It can be 'expand', 'reduce', or 'broadcast'.
### args: Additional arguments to pass to the function.

In [ ]:
q_restuarant["score"]=q_restuarant.apply(weighted_rating,axis=1)

In [ ]:
q_restuarant

,Restaurant Name,Cuisines,Locality,Aggregate rating,Votes,score
884,Berco's,"Chinese, Thai","Crown Interiorz Mall, Sector 35, Faridabad",3.8,508,3.357177
891,Barbeque Nation,North Indian,"Crown Interiorz Mall, Sector 35, Faridabad",4.0,299,3.295732
892,Yo! China,Chinese,"Crown Interiorz Mall, Sector 35, Faridabad",4.1,239,3.256924
943,Cafe Parmesan,Italian,Sector 15,4.5,799,4.023355
949,Chickenette,"Raw Meats, North Indian, Chinese, Fast Food",Sector 15,3.7,280,3.106275
...,...,...,...,...,...,...
9090,Crazy Noodles,"Chinese, Thai","The Great India Place, Sector 38",3.6,507,3.219737
9092,Mandarin Trail,Chinese,"The Great India Place, Sector 38",3.7,517,3.293642
9096,TGI Friday's,"American, Tex-Mex","The Great India Place, Sector 38",3.5,1147,3.312907
9097,Thaal Vaadi,"North Indian, Rajasthani","The Great India Place, Sector 38",3.5,249,2.965063
9107,The Punjabiis Restro Bar,"North Indian, Chinese","The Great India Place, Sector 38",4.0,395,3.403220

### df.sort_values()
### The sort_values() method in pandas is used to sort a DataFrame by one or more columns.

In [ ]:
import pandas as pd

# Example DataFrame
df = pd.DataFrame({'A': [3, 1, 2], 'B': ['b', 'a', 'c']})

# Sorting DataFrame by column 'A' in ascending order
sorted_df = df.sort_values(by='A')
print(sorted_df)

   A  B
1  1  a
2  2  c
0  3  b

In [ ]:
q_restuarant=q_restuarant.sort_values("score",ascending=False)

In [ ]:
q_restuarant

,Restaurant Name,Cuisines,Locality,Aggregate rating,Votes,score
3013,Naturals Ice Cream,Ice Cream,Connaught Place,4.9,2620,4.694683
3601,Indian Accent - The Manor,Modern Indian,Friends Colony,4.9,1934,4.629716
1839,Prankster,"Modern Indian, North Indian",Sector 29,4.8,1478,4.471393
4638,Big Chill,"Italian, Continental, European, Cafe",Khan Market,4.5,4986,4.405675
6997,Echoes Satyaniketan,"Cafe, Continental, Italian, Mexican, Chinese, ...",Satyaniketan,4.7,1563,4.399958
...,...,...,...,...,...,...
6450,Domino's Pizza,"Pizza, Fast Food",PVR Anupam Complex,2.5,253,2.449949
8739,Yo! China,Chinese,Sector 50,2.5,252,2.449846
3786,Domino's Pizza,"Pizza, Fast Food",Green Park,2.5,238,2.448359
1247,The Wine Company,"Italian, European","Cyber Hub, DLF Cyber City",2.4,2412,2.399632
5957,Comesum,"Fast Food, North Indian, South Indian",Nizamuddin,2.2,251,2.294485

In [ ]:
q_restuarant.head(10)

,Restaurant Name,Cuisines,Locality,Aggregate rating,Votes,score
3013,Naturals Ice Cream,Ice Cream,Connaught Place,4.9,2620,4.694683
3601,Indian Accent - The Manor,Modern Indian,Friends Colony,4.9,1934,4.629716
1839,Prankster,"Modern Indian, North Indian",Sector 29,4.8,1478,4.471393
4638,Big Chill,"Italian, Continental, European, Cafe",Khan Market,4.5,4986,4.405675
6997,Echoes Satyaniketan,"Cafe, Continental, Italian, Mexican, Chinese, ...",Satyaniketan,4.7,1563,4.399958
1464,Manhattan Brewery & Bar Exchange,"Finger Food, American, Continental, North Indi...","Global Foyer Mall, Golf Course Road",4.6,2093,4.378352
6659,The California Boulevard,"American, Asian, European, Seafood",Rajouri Garden,4.6,1691,4.332065
4639,Big Chill,"Italian, Continental, European, Cafe",Khan Market,4.6,1569,4.313935
6317,Cafe Lota,"North Indian, South Indian, Bihari",Pragati Maidan,4.5,2213,4.298784
6144,Gulati,"North Indian, Mughlai",Pandara Road Market,4.4,4373,4.298204